'use strict';

module.exports = {
  title: 'Gebruik van de Opdracht',
  titleError: 'Fout :warning:',
  titleComp: 'Voltooien :white_check_mark:',
  unknownChannel: 'Onbekende zender.',
  unknownRole: 'De rol van het onbekend.',
  unknownMessage: 'Onbekend bericht.',
  unknownEmoji: 'Onbekende emoji.',
  noChannel: ['Stel een kanaal eerst met **', 'channel**.'],
  noMessage: ['Stel een bericht om te gebruiken met **', 'message**.'],
  help: {
    commandsTitle: 'Opdrachten',
    commands: {
      channel: 'stel het kanaal dat u wilt gebruiken instellen\n',
      message: 'het bericht dat u wilt gebruiken instellen\n',
      add: 'een rol met een emoji toevoegen\n',
      toggle: 'een functie die kan worden toggled toevoegen\n',
      remove: 'verwijderen van een functie die is ingesteld\n',
      edit: 'bewerken van een bericht wordt verzonden door Zira\n',
      list: 'lijst van de rollen wordt gebruikt\n',
      autorole: 'gebruikers en bots een rol te geven op join\n',
      log: 'logboek wanneer Zira geeft\n',
      join: 'stuurt een bericht wanneer een gebruiker lid wordt\n',
      leave: 'stuurt een bericht wanneer een gebruiker verlaat\n',
      lang: 'locale instellen\n',
      reset: 'resetten van de config van de gilde\n',
      info: 'meer weten over Zira\n',
      faq: 'veel gestelde vragen\n',
      ping: 'Zira van ping\n',
      invite: 'uitnodigen van Zira\n',
      suggestion: 'stel het kanaal gebruiken voor suggesties\n',
      submit: 'indienen van een suggestie\n',
      approve: 'instellen van een suggestie als een goedgekeurde suggestie\n',
      maybe: 'instellen van een suggestie als een potentieel goedgekeurde suggestie\n',
      deny: 'instellen van een suggestie als een geweigerde suggestie\n',
      once: 'toevoegen van een rol die eenmaal kan worden uitgekeerd\n',
      calc: 'rekenmachine\n',
      purge: 'maximaal 100 berichten wissen\n',
    },
    categories: {
      role: 'Rollen',
      logs: 'Logboekregistratie',
      suggestion: 'Suggesties',
      misc: 'Diversen',
    },
    linksTitle: 'Koppelingen',
    links: '[Gids aan opstelling Zira](https://demo.zira.pw)\n[Ondersteuning gilde](https://zira.pw/support)\n[Zira\'s Dashboard](https://zira.pw)\n[Doneer van Zira actief houden](https://www.patreon.com/HazedSPaCEx)\n[Vertaal Zira](https://github.com/HazedSPaCEx/Zira-Translations)',
    news: 'Nieuws',
  },
  channel: {
    help: 'channel #channel** ~~-~~ stel het kannal dat wordt gebruikt',
    set: 'Kanaal ingesteld op <#',
  },
  message: {
    help: 'message [[message ID](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) | message]** ~~-~~ gebruik een bestaand bericht, of maak een nieuwe',
    cannotSend: ['Stuur een bericht naar kunnen <#', '> omdat ik niet over de machtiging `Verzenden Berichten`.'],
    cannotRead: ['Stuur een bericht naar kunnen <#', '> omdat i niet over de machtiging `Lezen Berichten` of `Lezen bericht geschiedenis`.'],
    unknown: 'Kaan geen bericht verzenden.',
    cannotReadID: ['Niet in staat om de boodschap van <#', '> omdat ik niet over de machtiging `Lezen berichten` of `Lezen bericht geschiedenis`.'],
    unknownID: 'Niet in staat te stellen de bericht-ID.',
    set: 'Bericht instellen met de ID van ',
  },
  add: {
    help: 'add [emoji] [@role | role name]** ~~-~~ een rol met een emoji toevoegen aan het bericht instellen',
    cannotRead: ['Niet in staat om te reageren op het bericht in <#', '> omdat ik niet over de machtiging `Lezen berichten` of `Lezen bericht geschiedenis`.'],
    cannotReact: ['Niet in staat om te reageren op het bericht in <#', '> omdat ik niet over de machtiging `Reactie toevoegen`.'],
    unknown: 'Niet in staat om te reageren op het bericht in <#',
    set: ['<@&', '> met de emoji toegevoegd', '\n\n**OPMERKING:** de rol `Zira` moet boven de rol die u hebt ingesteld, en moet beschikken over de machtiging `Rollen beheren` om deze rol te geven.'],
    emoji: 'Dat emoji is al in gebruik op dit bericht.',
    role: 'Die rol is al in gebruik op dit bericht.',
  },
  toggle: {
    help: 'toggle [emoji] [@role | role name]** ~~-~~ een rol met een emoji toevoegen aan het bericht instellen',
    image: 'https://stuff.zira.pw/files/1524932965273.gif', /* Ik zal dit vervangen door een gif dat is snel als mijn internet en laptop is traag */
  },
  perm: {
    noPerm: 'U moet de eigenaar van de gilde, of de `MANAGE_ROLES` permanent als deze opdrachten wilt gebruiken.',
    noLangPerm: 'U moet de eigenaar van de gilde of hebben de `MANAGE_GUILD` permanent de bot taal wijzigen.',
    noMessagePerm: 'U moet de eigenaar van de gilde of beschikken over de machtiging `MANAGE_MESSAGES` berichten verwijderen.',
    noGuildPerm: 'U moet de eigenaar van de gilde of beschikken over de machtiging `MANAGE_GUILD` gebruik van deze opdracht.',
  },
  lang: {
    langUpdate: 'Taal bijgewerkt.',
    translate: 'Als u wilt dat Zira in een taal die niet op de bovenstaande lijst,\nu kunt helpen vertalen [hier](https://github.com/HazedSPaCEx/Zira-Translations)',
  },
  log: {
    title: 'Log Command',
    help: ['log #channel** ~~-~~ set the channel for logging\n\nTo stop logging, do **', 'log stop**\n\nAn example of a message is below'],
    set: ['Log channel set to <#', '>\n\n**NOTE:** If Zira is not able to send to the channel, logging will be disabled.'],
    stop: 'Log messages will no longer be sent.',
    image: 'https://stuff.zira.pw/files/logExample.png',
    give: [' reacted ', ' to get '],
    remove: [' unreacted ', ' to remove '],
  },
  faq: {
    title: 'Frequently Asked Questions',
    fields: [{
      name: 'Whenever I do commands, Zira doesn\'t send messages, what do I do?',
      value: 'Make sure Zira has permission to embed links and send messages in the channel you are trying the commands in.',
    }, {
      name: 'Zira says `"Can\'t find a message with that ID"` or `"Unknown message ID"`, what do I do?',
      value: 'Make sure that the message ID is in the channel you\'ve set, and that Zira is able to read the channel',
    }, {
      name: 'Even though I set it up properly, Zira doesn\'t give roles.',
      value: 'Make sure Zira has permission to manage roles, and that the "Zira" role is above the roles you\'ve setup.',
    }, {
      name: 'Is Zira able to remove emojis that don\'t have a corresponding role setup with them?',
      value: 'Yes, but you must allow Zira to `manage messages` in the channel you\'ve setup.',
    }, {
      name: 'Is Zira able to handle more than one message?',
      value: 'Yes, just set another message, and add roles to that message.',
    }, {
      name: 'Is Zira able to handle more than one channel?',
      value: 'Yes, just set another channel, then message, etc.',
    }, {
      name: 'How many roles are allowed per message?',
      value: 'Since Discord only allows 20 emojis per message, 20 roles are allowed per message.',
    }],
  },
  join: {
    title: 'Join Command',
    help: ['join channel** ~~-~~ set the channel that messages will be sent to\n**', 'join message** ~~-~~ set the message that will be sent when a user joins\n\nYou can use these placeholders in the message:\n$user ~~-~~ username\n$mention ~~-~~ user mention\n$guild ~~-~~ guild name\n$membercount ~~-~~ new member count'],
    channel: ['join channel #channel** ~~-~~ set the channel that join messages will be sent to\n\nTo stop sending to the channel set, do **', 'join channel stop**'],
    stop: 'Join messages will no longer be sent.',
    setChannel: ['Channel set to <#', '>\n\n**NOTE:** If Zira is not able to send messages to the channel, join messages will be disabled.'],
    message: 'join message [message]** ~~-~~ set the message that will be sent when a user joins\n\nYou can use these placeholders in the message:\n$user ~~-~~ username\n$mention ~~-~~ user mention\n$guild ~~-~~ guild name\n$membercount ~~-~~ new member count',
    setMessage: 'Join message set to:\n',
  },
  leave: {
    title: 'Leave Command',
    help: ['leave channel** ~~-~~ set the channel that messages will be sent to\n**', 'leave message** ~~-~~ set the message that will be sent when a user leave\n\nYou can use these placeholders in the message:\n$user ~~-~~ username\n$mention ~~-~~ user mention\n$guild ~~-~~ guild name\n$membercount ~~-~~ new member count'],
    channel: ['leave channel #channel** ~~-~~ set the channel that leave messages will be sent to\n\nTo stop sending to the channel set, do **', 'leave channel stop**'],
    stop: 'Leave messages will stop being sent.',
    setChannel: ['Channel set to <#', '>\n\n**NOTE:** If Zira is not able to send messages to the channel, leave messages will be disabled.'],
    message: 'leave message [message]** ~~-~~ set the message that will be sent when a user leaves\n\nYou can use these placeholders in the message:\n$user ~~-~~ username\n$mention ~~-~~ user mention\n$guild ~~-~~ guild name\n$membercount ~~-~~ new member count',
    setMessage: 'Leave message set to:\n',
  },
  auto: {
    title: 'Auto Role',
    help: ['autorole show** ~~-~~ show the current roles set\n**', 'autorole user** ~~-~~ add or remove roles that should be given on user join\n**', 'autorole bot** ~~-~~ add or remove roles that should be given on bot join'],
    user: 'autorole user [@role | role name]** ~~-~~ add or remove a role that should be given when a user joins\n\nTo remove a role that has been set do the above command.',
    userAdd: ['Added role <@&', '> that will be given when a user joins.\n\n**NOTE:** The `Zira` role needs to be above the role you\'ve set, and needs to have the `Manage Roles` permission to give this role.'],
    userRemove: ['Removed role <@&', '> from being given when a user joins.'],
    botAdd: ['Added role <@&', '> that will be given when a bot is invited.\n\n**NOTE:** The `Zira` role needs to be above the role you\'ve set, and needs to have the `Manage Roles` permission to give this role.'],
    botRemove: ['Removed role <@&', '> from being given when a bot invited.'],
    bot: 'autorole bot [@role | role name]** ~~-~~ add or remove a role that should be given when a bot is invited\n\nTo remove a role that has been set, do the above command.',
    showUser: 'User Roles',
    showBot: 'Bot Roles',
    no: 'No roles set.',
  },
  reset: {
    title: 'Config Reset :warning:',
    question: 'Are you sure you want to reset the guild config?\n**EVERYTHING** setup through Zira will be reset.\n\nType `yes` or `no`',
    yes: 'Guild config has been reset.',
    no: 'Nothing has been reset.',
    perm: 'Only the owner of the guild can reset the config.',
  },
  list: {
    title: ' Role List',
    cont: 'List Continued',
    null: 'If a message ID is null, either reset your config and read the roles, or join the [support server](https://zira.pw/support).',
    noTitle: 'OwO',
    noDesc: 'What\'s this?',
  },
  remove: {
    help: ['remove [[message ID](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)] [@role | role name]** ~~-~~ remove a role that has been setup by Zira\n\nTo get the message ID that a role is on, do **', 'list**.'],
    setup: 'Unable to remove the role as it either was not setup by Zira, or is not on the specified message.',
    removed: ['<@&', '> removed with the emoji '],
  },
  edit: {
    help: 'edit [[message ID](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)] [new message]** ~~-~~ edit a message sent by Zira',
    read: ['Unable to get the message in <#', '> because I lack the `Read Messages` or `Read Message History` permissions.'],
    unknownGet: 'Unable to get that message in <#',
    unknownEdit: 'Unable to edit the message.',
    no: 'That message can\'t be edited by Zira, as it was not sent by Zira.',
    edited: 'Message has been edited.',
  },
  suggestion: {
    help: ['suggestion #channel** ~~-~~ set a channel that suggestions will be sent to\nIf you want to only allow suggestions to be submitted in one channel, do **', 'suggestion [#suggestion channel] [#submit channel]**\n\nTo disable suggestions, do **', 'suggestion stop**'],
    set: ['Suggestion channel set to <#', '>\n\n**NOTE:** If Zira is not able to send messages to the channel, suggestions will be disabled.'],
    setsubmit: ['Suggestion channel set to <#', '> and suggestions can only be submitted in <#', '>\n\n**NOTE:** If Zira is not able to send messages to the channel, suggestions will be disabled.'],
    stop: 'Suggestions are now disabled.',
    disable: 'Suggestions are disabled.',
    notSetup: 'That message is not a suggestion sent by Zira.',
    reason: 'Reason',
    useChannel: ['Use the channel <#', '> to submit a suggestion.'],
    noReason: 'No reason was provided.',
  },
  submit: {
    help: 'submit [suggestion]** ~~-~~ submit your wonderful suggestion',
    title: 'New Suggestion',
  },
  approve: {
    help: 'approve [[message ID](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)] [reason]** ~~-~~ approve a suggestion',
    read: ['Unable to approve the suggestion in <#', '> because I lack the `Read Messages` or `Read Message History` permissions.'],
    title: 'Approved Suggestion',
    reason: 'Reason',
    unknown: 'Unable to approve suggestion.',
  },
  deny: {
    help: 'deny [[message ID](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)] [reason]** ~~-~~ deny a suggestion',
    read: ['Unable to deny the suggestion in <#', '> because I lack the `Read Messages` or `Read Message History` permissions.'],
    title: 'Denied Suggestion',
    unknown: 'Unable to deny suggestion.',
  },
  maybe: {
    help: 'maybe [[message ID](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)] [reason]** ~~-~~ potentially approve a suggestion',
    read: ['Unable to potentially approve the suggestion in <#', '> because I lack the `Read Messages` or `Read Message History` permissions.'],
    title: 'Potential Suggestion',
    unknown: 'Unable to potentially approve suggestion.',
  },
  once: {
    help: 'once [emoji] [@role | role name]** ~~-~~ add a role with an emoji that can only be claimed once to the set message\n\nThis is useful for accepting guild rules, etc.',
    cannotRead: ['Unable to react to the message in <#', '> because I lack the `Read Messages` or `Read Message History` permissions.'],
    cannotReact: ['Unable to react to the message in <#', '> because I lack the `Add Reaction` permission.'],
    unknown: 'Unable to react to the message in <#',
    set: ['<@&', '> added with the emoji ', '\n\n**NOTE:** The `Zira` role needs to be above the role you\'ve set, and needs to have `Manage Roles` permission to give this role.'],
    emoji: 'That emoji is already in use on this message.',
    role: 'That role is already in use on this message.',
  },
  purge: {
    amount: 'You didn\'t input an amount of messages.',
    wrongAmount: 'The amount of messages can only be between 2 - 100.',
    error: 'Couldn\'t purge messages.',
  },

};
