'use strict';

module.exports = {
  title: 'Gebruik van de Opdracht',
  titleError: 'Fout :warning:',
  titleComp: 'Voltooien :white_check_mark:',
  unknownChannel: 'Onbekende zender.',
  unknownRole: 'De rol van het onbekend.',
  unknownMessage: 'Onbekend bericht.',
  unknownEmoji: 'Onbekende emoji.',
  noChannel: ['Stel een kanaal eerst met **', 'channel**.'],
  noMessage: ['Stel een bericht om te gebruiken met **', 'message**.'],
  help: {
    commandsTitle: 'Opdrachten',
    commands: {
      channel: 'stel het kanaal dat u wilt gebruiken instellen\n',
      message: 'het bericht dat u wilt gebruiken instellen\n',
      add: 'een rol met een emoji toevoegen\n',
      toggle: 'een functie die kan worden toggled toevoegen\n',
      remove: 'verwijderen van een functie die is ingesteld\n',
      edit: 'bewerken van een bericht wordt verzonden door Zira\n',
      list: 'lijst van de rollen wordt gebruikt\n',
      autorole: 'gebruikers en bots een rol te geven op join\n',
      log: 'logboek wanneer Zira geeft\n',
      join: 'stuurt een bericht wanneer een gebruiker lid wordt\n',
      leave: 'stuurt een bericht wanneer een gebruiker verlaat\n',
      lang: 'locale instellen\n',
      reset: 'resetten van de config van de gilde\n',
      info: 'meer weten over Zira\n',
      faq: 'veel gestelde vragen\n',
      ping: 'Zira van ping\n',
      invite: 'uitnodigen van Zira\n',
      suggestion: 'stel het kanaal gebruiken voor suggesties\n',
      submit: 'indienen van een suggestie\n',
      approve: 'instellen van een suggestie als een goedgekeurde suggestie\n',
      maybe: 'instellen van een suggestie als een potentieel goedgekeurde suggestie\n',
      deny: 'instellen van een suggestie als een geweigerde suggestie\n',
      once: 'toevoegen van een rol die eenmaal kan worden uitgekeerd\n',
      calc: 'rekenmachine\n',
      purge: 'maximaal 100 berichten wissen\n',
    },
    categories: {
      role: 'Rollen',
      logs: 'Logboekregistratie',
      suggestion: 'Suggesties',
      misc: 'Diversen',
    },
    linksTitle: 'Koppelingen',
    links: '[Gids aan opstelling Zira](https://demo.zira.pw)\n[Ondersteuning gilde](https://zira.pw/support)\n[Zira\'s Dashboard](https://zira.pw)\n[Doneer van Zira actief houden](https://www.patreon.com/HazedSPaCEx)\n[Vertaal Zira](https://github.com/HazedSPaCEx/Zira-Translations)',
    news: 'Nieuws',
  },
  channel: {
    help: 'channel #channel** ~~-~~ stel het kannal dat wordt gebruikt',
    set: 'Kanaal ingesteld op <#',
  },
  message: {
    help: 'message [[message ID](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) | message]** ~~-~~ gebruik een bestaand bericht, of maak een nieuwe',
    cannotSend: ['Stuur een bericht naar kunnen <#', '> omdat ik niet over de machtiging `Verzenden Berichten`.'],
    cannotRead: ['Stuur een bericht naar kunnen <#', '> omdat i niet over de machtiging `Lezen Berichten` of `Lezen bericht geschiedenis`.'],
    unknown: 'Kaan geen bericht verzenden.',
    cannotReadID: ['Niet in staat om de boodschap van <#', '> omdat ik niet over de machtiging `Lezen berichten` of `Lezen bericht geschiedenis`.'],
    unknownID: 'Niet in staat te stellen de bericht-ID.',
    set: 'Bericht instellen met de ID van ',
  },
  add: {
    help: 'add [emoji] [@role | role name]** ~~-~~ een rol met een emoji toevoegen aan het bericht instellen',
    cannotRead: ['Niet in staat om te reageren op het bericht in <#', '> omdat ik niet over de machtiging `Lezen berichten` of `Lezen bericht geschiedenis`.'],
    cannotReact: ['Niet in staat om te reageren op het bericht in <#', '> omdat ik niet over de machtiging `Reactie toevoegen`.'],
    unknown: 'Niet in staat om te reageren op het bericht in <#',
    set: ['<@&', '> met de emoji toegevoegd', '\n\n**OPMERKING:** de rol `Zira` moet boven de rol die u hebt ingesteld, en moet beschikken over de machtiging `Rollen beheren` om deze rol te geven.'],
    emoji: 'Dat emoji is al in gebruik op dit bericht.',
    role: 'Die rol is al in gebruik op dit bericht.',
  },
  toggle: {
    help: 'toggle [emoji] [@role | role name]** ~~-~~ een rol met een emoji toevoegen aan het bericht instellen',
    image: 'https://stuff.zira.pw/files/1524932965273.gif', /* Ik zal dit vervangen door een gif dat is snel als mijn internet en laptop is traag */
  },
  perm: {
    noPerm: 'U moet de eigenaar van de gilde, of de `MANAGE_ROLES` permanent als deze opdrachten wilt gebruiken.',
    noLangPerm: 'U moet de eigenaar van de gilde of hebben de `MANAGE_GUILD` permanent de bot taal wijzigen.',
    noMessagePerm: 'U moet de eigenaar van de gilde of beschikken over de machtiging `MANAGE_MESSAGES` berichten verwijderen.',
    noGuildPerm: 'U moet de eigenaar van de gilde of beschikken over de machtiging `MANAGE_GUILD` gebruik van deze opdracht.',
  },
  lang: {
    langUpdate: 'Taal bijgewerkt.',
    translate: 'Als u wilt dat Zira in een taal die niet op de bovenstaande lijst,\nu kunt helpen vertalen [hier](https://github.com/HazedSPaCEx/Zira-Translations)',
  },
  log: {
    title: 'Log Commando',
    help: ['log #channel** ~~-~~ stel het kanaal voor aanmelding\n\nAls u wilt stoppen met vastleggen, doen **', 'log stop**\n\nEen voorbeeld van een bericht is hieronder'],
    set: ['Log channel set toLog kannal ingesteld op <#', '>\n\n**OPMERKING:** als Zira kunnen sturen naar het kanaal, logboekregistratie wordt uitgeschakeld.'],
    stop: 'Logboekberichten worden niet langer verzonden.',
    image: 'https://stuff.zira.pw/files/logExample.png',
    give: [' reageerde ', ' om te krijgen '],
    remove: [' spoorverontreiniging ', ' om te verwijderen '],
  },
  faq: {
    title: 'Veelgestelde Vragen',
    fields: [{
      name: 'Wanneer ik opdrachten, Zira niet berichten verzenden, wat moet ik doen?',
      value: 'Zorg ervoor dat Zira toegangsmachtiging voor het insluiten van koppelingen en berichten verzenden in het kanaal dat u probeert de commando\'s in.',
    }, {
      name: 'Zira zegt `"kan niet een bericht met die ID"` of `"Unknown message ID"`, wat moet ik doen?',
      value: 'Zorg ervoor dat het bericht-ID, het kanaal wordt dat u hebt ingesteld, en dat Zira is in staat om te lezen van het kanaal.',
    }, {
      name: 'Hoewel ik het correct ingesteld, geven Zira rollen niet.',
      value: 'Zorg ervoor dat Zira machtiging voor het beheren van rollen, en dat de rol van "Zira" boven de rollen u hebt setup.',
    }, {
      name: 'Is Zira kundig voor wegnemen emojis waarvoor geen een overeenkomstige rol setup met hen?',
      value: 'Ja, maar je moet toestaan dat Zira `berichten beheren` in het kanaal u hebt setup.',
    }, {
      name: 'Vermag Zira Steel meer dan één bericht?',
      value: 'Ja, gewoon een ander bericht instellen en rollen aan dit bericht toevoegen.',
    }, {
      name: 'Zira in staat om meer dan één kanaal is?',
      value: 'Ja, stel een ander kanaal, dan bericht, enz.',
    }, {
      name: 'Hoeveel rollen zijn toegestaan per bericht?',
      value: 'Aangezien slechts onenigheid 20 emojis per bericht toestaat, zijn 20 rollen toegestaan per bericht.',
    }],
  },
  join: {
    title: 'De opdracht verbinden',
    help: ['join channel** ~~-~~ stel het kanaal dat berichten worden verzonden naar\n**', 'join message** ~~-~~ het bericht dat wordt verzonden wanneer een gebruiker voegt instellen\n\nU kunt deze tijdelijke aanduidingen in het bericht:\n$user ~~-~~ gebruikersnaam\n$mention ~~-~~ vermelding van de gebruiker\n$guild ~~-~~ gilde-naam\n$membercount ~~-~~ nieuwe lidstaten tellen'],
    channel: ['join channel #channel** ~~-~~ stel het kanaal dat berichten worden verzonden naar join\n\nOm te stoppen met het verzenden naar de kanaal set, doen **', 'join channel stop**'],
    stop: 'Lid worden berichten niet langer worden verzonden.',
    setChannel: ['Kanaal ingesteld op <#', '>\n\n**OPMERKING:** Als Zira kan geen berichten verzenden naar het kanaal, wordt join-berichten uitgeschakeld.'],
    message: 'join message [message]** ~~-~~ het bericht dat wordt verzonden wanneer een gebruiker voegt instellen\n\nU kunt deze tijdelijke aanduidingen in het bericht:\n$user ~~-~~ gebruikersnaam\n$mention ~~-~~ vermelding van de gebruiker\n$guild ~~-~~ gild-naam\n$membercount ~~-~~ nieuwe lidstaten tellen',
    setMessage: 'Deelnemen aan bericht is ingesteld op:\n',
  },
  leave: {
    title: 'Verlaten van de opdracht',
    help: ['leave channel** ~~-~~ stel het kanaal dat berichten worden verzonden naar\n**', 'leave message** ~~-~~ instellen van het bericht dat wordt verzonden wanneer een gebruiker verlaat\n\nU kunt deze tijdelijke aanduidingen in het bericht:\n$user ~~-~~ gebruikersnaam\n$mention ~~-~~ vermelding van de gebruiker\n$guild ~~-~~ gilde-naam\n$membercount ~~-~~ nieuwe lidstaten tellen'],
    channel: ['leave channel #channel** ~~-~~ stel het kanaal dat berichten worden verzonden naar verlof\n\nOm te stoppen met het verzenden naar de kanaal set, doen **', 'leave channel stop**'],
    stop: 'Laat berichten stopt wordt verzonden.',
    setChannel: ['Kanaal ingesteld op <#', '>\n\n**OPMERKING:** Als Zira kan geen berichten verzenden naar het kanaal, laat wordt berichten uitgeschakeld.'],
    message: 'leave message [message]** ~~-~~ instellen van het bericht dat wordt verzonden wanneer een gebruiker verlaat\n\nU kunt deze tijdelijke aanduidingen in het bericht:\n$user ~~-~~ gebruikersnaam\n$mention ~~-~~ vermelding van de gebruiker\n$guild ~~-~~ gilde-naam\n$membercount ~~-~~ nieuwe lidstaten tellen',
    setMessage: 'Laat bericht ingesteld op:\n',
  },
  auto: {
    title: 'Rol van de auto',
    help: ['autorole show** ~~-~~ Toon de huidige set van rollen.\n**', 'autorole user** ~~-~~ toevoegen of verwijderen van rollen die moeten worden gegeven over gebruiker join\n**', 'autorole bot** ~~-~~ toevoegen of verwijderen van rollen die moeten worden gegeven over het bot join'],
    user: 'autorole user [@role | role name]** ~~-~~ toevoegen of verwijderen van een rol die moet worden gegeven als een gebruiker wordt toegevoegd aan\n\nAls u wilt verwijderen van een rol die al reeks doen het bovenstaande commando.',
    userAdd: ['Toegevoegde rol <@&', '> die krijgt wanneer een gebruiker voegt.\n\n**OPMERKING:** De rol van `Zira` moet boven de rol die u hebt ingesteld, en moet beschikken over de machtiging `Rollen beheren` om deze rol te geven.'],
    userRemove: ['Verwijderde rol <@&', '> van wordt gegeven wanneer een gebruiker lid wordt.'],
    botAdd: ['Toegevoegde rol <@&', '> die zal worden gegeven als een bot is uitgenodigd.\n\n**OPMERKING:** de rol `Zira` moet boven de rol die u hebt ingesteld, en moet beschikken over de machtiging `Rollen beheren` om deze rol te geven.'],
    botRemove: ['Verwijderde rol <@&', '> van wordt gegeven wanneer een bot uitgenodigd.'],
    bot: 'autorole bot [@role | role name]** ~~-~~ toevoegen of verwijderen van een rol die moet worden gegeven als een bot wordt verzocht\n\nAls u wilt verwijderen een rol dat is vastgesteld, doen de bovenstaande commando.',
    showUser: 'Gebruikersrollen',
    showBot: 'Bot rollen',
    no: 'Geen rollen instellen.',
  },
  reset: {
    title: 'Resetten van de config :warning:',
    question: 'Weet u zeker dat u wilt herstellen van de gilde-config?\n**ALLES** setup via Zira zal worden teruggesteld.\n\nType `yes` of `no`',
    yes: 'Gilde config zijn hersteld.',
    no: 'Niets zijn hersteld.',
    perm: 'Alleen de eigenaar van het gilde kunt resetten van de config.',
  },
  list: {
    title: 'Lijst van de rol',
    cont: 'Lijst voortgezet',
    null: 'Als een bericht-ID leeg is, ofwel reset je config en lees de rollen, of deelnemen aan de [ondersteuning-server](https://zira.pw/support).',
    noTitle: 'OwO',
    noDesc: 'Wat is dit?',
  },
  remove: {
    help: ['remove [[bericht-ID](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)] [@role | role name]** ~~-~~ verwijderen van een functie die ingesteld door Zira is\n\nAls u de bericht-ID, die een rol op, doen **', 'list**.'],
    setup: 'Kan niet verwijderen van de rol als het was niet ingesteld door Zira of is niet op het opgegeven bericht.',
    removed: ['<@&', '> verwijderd met de emoji '],
  },
  edit: {
    help: 'edit [[bericht-ID](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)] [new message]** ~~-~~ een bericht wordt verzonden door Zira bewerken',
    read: ['Niet in staat om het bericht <#', '> omdat ik niet de machtigingen `Lezen berichten` of `Lezen bericht geschiedenis`.'],
    unknownGet: 'Niet in staat om die boodschap <#',
    unknownEdit: 'Kan niet het bericht te bewerken.',
    no: 'Dat bericht kan niet worden bewerkt door Zira, aangezien het niet door Zira was gezonden.',
    edited: 'Bericht is bewerkt.',
  },
  suggestion: {
    help: ['suggestion #channel** ~~-~~ set a channel that suggestions will be sent to\nIf you want to only allow suggestions to be submitted in one channel, do **', 'suggestion [#suggestion channel] [#submit channel]**\n\nTo disable suggestions, do **', 'suggestion stop**'],
    set: ['Suggestion channel set to <#', '>\n\n**NOTE:** If Zira is not able to send messages to the channel, suggestions will be disabled.'],
    setsubmit: ['Suggestion channel set to <#', '> and suggestions can only be submitted in <#', '>\n\n**NOTE:** If Zira is not able to send messages to the channel, suggestions will be disabled.'],
    stop: 'Suggestions are now disabled.',
    disable: 'Suggestions are disabled.',
    notSetup: 'That message is not a suggestion sent by Zira.',
    reason: 'Reason',
    useChannel: ['Use the channel <#', '> to submit a suggestion.'],
    noReason: 'No reason was provided.',
  },
  submit: {
    help: 'submit [suggestion]** ~~-~~ submit your wonderful suggestion',
    title: 'New Suggestion',
  },
  approve: {
    help: 'approve [[message ID](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)] [reason]** ~~-~~ approve a suggestion',
    read: ['Unable to approve the suggestion in <#', '> because I lack the `Read Messages` or `Read Message History` permissions.'],
    title: 'Approved Suggestion',
    reason: 'Reason',
    unknown: 'Unable to approve suggestion.',
  },
  deny: {
    help: 'deny [[message ID](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)] [reason]** ~~-~~ deny a suggestion',
    read: ['Unable to deny the suggestion in <#', '> because I lack the `Read Messages` or `Read Message History` permissions.'],
    title: 'Denied Suggestion',
    unknown: 'Unable to deny suggestion.',
  },
  maybe: {
    help: 'maybe [[message ID](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)] [reason]** ~~-~~ potentially approve a suggestion',
    read: ['Unable to potentially approve the suggestion in <#', '> because I lack the `Read Messages` or `Read Message History` permissions.'],
    title: 'Potential Suggestion',
    unknown: 'Unable to potentially approve suggestion.',
  },
  once: {
    help: 'once [emoji] [@role | role name]** ~~-~~ add a role with an emoji that can only be claimed once to the set message\n\nThis is useful for accepting guild rules, etc.',
    cannotRead: ['Unable to react to the message in <#', '> because I lack the `Read Messages` or `Read Message History` permissions.'],
    cannotReact: ['Unable to react to the message in <#', '> because I lack the `Add Reaction` permission.'],
    unknown: 'Unable to react to the message in <#',
    set: ['<@&', '> added with the emoji ', '\n\n**NOTE:** The `Zira` role needs to be above the role you\'ve set, and needs to have `Manage Roles` permission to give this role.'],
    emoji: 'That emoji is already in use on this message.',
    role: 'That role is already in use on this message.',
  },
  purge: {
    amount: 'You didn\'t input an amount of messages.',
    wrongAmount: 'The amount of messages can only be between 2 - 100.',
    error: 'Couldn\'t purge messages.',
  },

};
