'use strict';

module.exports = {
  title: 'Command Usage',
  titleError: 'Erro :warning:',
  titleComp: 'Completo :white_check_mark:',
  unknownChannel: 'Canal desconhecido.',
  unknownRole: 'Cargo desconhecido.',
  unknownMessage: 'Mensagem desconhecida.',
  unknownEmoji: 'Emoji desconhecido.',
  noChannel: ['Por favor defina um canal primeiro com **', 'channel**.'],
  noMessage: ['Por favor defina uma mensagem para usar com **', 'message**.'],
  help: {
    commandsTitle: 'Comandos',
    commands: {
      channel: 'Defina o canal que quer usar\n',
      message: 'Defina a mensagem que quer usar\n',
      add: 'Adiciona um cargo com um emoji\n',
      toggle: 'Adiciona um cargo que pode ser alterado (adicionar/remover)\n',
      remove: 'Remove um cargo definido\n',
      edit: 'Edita uma mensagem enviada por Zira\n',
      list: 'Lista de cargos a serem usados\n',
      autorole: 'Atribui a utilizadores e a bots cargo ao entrar no servidor\n',
      log: 'Registo quando a Zira atribui/remove o cargo\n',
      join: 'Envia uma mensagem quando um utilizador entra\n',
      leave: 'Envia uma mensagem quando um utilizador sai\n',
      lang: 'Define o idioma\n',
      reset: 'Restablece as configurações do servidor\n',
      info: 'Informações sobre Zira\n',
      faq: 'Questões frequentes\n',
      ping: 'Zira\'s ping\n',
      invite: 'Convida Zira\n',
      suggestion: 'Defina o canal para usar como sugestões\n',
      submit: 'Envia a sugestão\n',
      approve: 'Define uma sugestão como sugestão aprovada\n',
      maybe: 'Define uma sugestão como uma potencial sugestão aprovada\n',
      deny: 'Define uma sugestão como sugestão negada\n',
      once: 'Adiciona um cargo que só pode ser obtido uma vez\n',
      calc: 'calculadora\n',
      purge: 'Elimina até 10 mensagens\n',
    },
    categories: {
      role: 'Cargos',
      logs: 'Registos',
      suggestion: 'Sugestões',
      misc: 'Diversos',
    },
    linksTitle: 'Links',
    links: '[Guia para configurar a Zira](https://demo.zira.pw)\n[Servidor de ajuda](https://zira.pw/support)\n[Dashboard da Zira](https://zira.pw)\n[Faça uma doação para a Zira continuar a funcionar](https://www.patreon.com/HazedSPaCEx)\n[Traduza Zira](https://github.com/HazedSPaCEx/Zira-Translations)',
    news: 'News',
  },
  channel: {
    help: 'channel #canal** ~~-~~ Define o canal que vai ser usado',
    set: 'Canal definido para <#',
  },
  message: {
    help: 'message [[ID da mensagem](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-) | message]** ~~-~~ use uma mensagem existente, ou crie uma nova',
    cannotSend: ['Impossivel enviar a mensagem para <#', '> porque falta-me permissões para `Enviar Mensagens`.'],
    cannotRead: ['Impossivel enviar a mensagem para <#', '> porque falta-me permissões para `Ler Mensagens` ou `Ler o Historico das Mensagens`.'],
    unknown: 'Impossivel enviar a mensagem.',
    cannotReadID: ['Impossivel conseguir a mensagem de <#', '> porque falta-me permissões para `Ler Mensagens` ou `Ler o Historico das Mensagens`.'],
    unknownID: 'Não encontrei o ID da mensagem.',
    set: 'Mensagem estabelecida com o ID de',
  },
  add: {
    help: 'add [emoji] [@cargo | nome do cargo]** ~~-~~ Adiciona um cargo com emoji à mensagem estabelecida',
    cannotRead: ['OPS! Não reagir à mensagem em <#', '> porque falta-me permissões para `Ler Mensagens` ou `Ler o Historico das Mensagens`.'],
    cannotReact: ['OPS! Não reagir à mensagem em <#', '> porque falta-me permissões para `Adicionar reações`.'],
    unknown: 'Não consigo reagir à mensagem em <#',
    set: [Cargo '<@&', '> adicionado com emoji ', '\n\n**NOTA:** O cargo `Zira` necessita estar acima do cargo que definiste, e precisa ter a permissão "Gerenciar Cargos" para atribuir cargos.'],
    emoji: 'Esse emoji já está a ser usado nesta menssagem.',
    role: 'Esse cargo já está a ser usado nesta menssagem.',
  },
  toggle: {
    help: 'toggle [emoji] [@role | role name]** ~~-~~ Adiciona um cargo com emoji à mensagem definida',
    image: 'https://stuff.zira.pw/files/1524932965273.gif', /* I will replace this with a gif that is fast as my internet and laptop is slow */
  },
  perm: {
    noPerm: 'Precisas de ser o dono , ou ter a permissão `Gerenciar Cargos` para usar estes comandos.',
    noLangPerm: 'Precisas de ser o dono , ou ter a permissão `Gerenciar Servidor` para trocar a lingua do bot.',
    noMessagePerm: 'Precisas de ser o dono , ou ter a permissão `Gerenciar Mensagens` para apagar mensagens.',
    noGuildPerm: 'Precisas de ser o dono , ou ter a permissão `Gerenciar Servidor` para usar este comando.',
  },
  lang: {
    langUpdate: 'Lingua atualizada.',
    translate: 'Se queres a Zira numa lingua que não está na lista abaixo,\n tu podes traduzir [aqui](https://github.com/HazedSPaCEx/Zira-Translations)',
  },
  log: {
    title: 'Comando Registo (Log)',
    help: ['log #canal** ~~-~~ Define o canal para registo\n\npara parar o registo, digite **', 'log stop**\n\nUm exemplo está abaixo'],
    set: ['Canal de registo definido para <#', '>\n\n**NOTA:** Se a Zira não tiver permissões para escrever no canal, o registo está desativado.'],
    stop: 'O Registo de mensagens não será mais enviado.',
    image: 'https://stuff.zira.pw/files/logExample.png',
    give: [' Reage a ', ' para conseguir o cargo '],
    remove: [' Reage de novo ', ' para remover o cargo '],
  },
  faq: {
    title: 'Questões Frequentes',
    fields: [{
      name: 'Whenever I do commands, Zira doesn\'t send messages, what do I do?',
      value: 'Make sure Zira has permission to embed links and send messages in the channel you are trying the commands in.',
    }, {
      name: 'Zira says `"Can\'t find a message with that ID"` or `"Unknown message ID"`, what do I do?',
      value: 'Make sure that the message ID is in the channel you\'ve set, and that Zira is able to read the channel',
    }, {
      name: 'Even though I set it up properly, Zira doesn\'t give roles.',
      value: 'Make sure Zira has permission to manage roles, and that the "Zira" role is above the roles you\'ve setup.',
    }, {
      name: 'Is Zira able to remove emojis that don\'t have a corresponding role setup with them?',
      value: 'Yes, but you must allow Zira to `manage messages` in the channel you\'ve setup.',
    }, {
      name: 'Is Zira able to handle more than one message?',
      value: 'Yes, just set another message, and add roles to that message.',
    }, {
      name: 'Is Zira able to handle more than one channel?',
      value: 'Yes, just set another channel, then message, etc.',
    }, {
      name: 'How many roles are allowed per message?',
      value: 'Since Discord only allows 20 emojis per message, 20 roles are allowed per message.',
    }],
  },
  join: {
    title: 'Comando join',
    help: ['join channel** ~~-~~ Define o canal que as mensagem vão ser enviadas\n**', 'join message** ~~-~~ Define a mensagem que vai ser enviado quando os users entram\n\nPodes usar estes comandos na mensagem:\n$user ~~-~~ username\n$mention ~~-~~ user mention\n$guild ~~-~~ nome do server\n$membercount ~~-~~ contagem novo membro'],
    channel: ['join channel #canal** ~~-~~ Define o canal que as mensagens de entrada serão enviadas\n\nPara parar de enviar mensagem para o canal, digite **', 'join channel stop**'],
    stop: 'As mensagens de entrada não serão mais enviadas.',
    setChannel: ['Canal definido para <#', '>\n\n**NOTA:** Se a Zira não poder enviar mensagens para o canal, as mensagens de entrada estarão desativadas.'],
    message: 'join message [menssagem]** ~~-~~ Define a mensagem que vai ser enviada quando o user entrar\n\nPodes usar estes comandos na mensagem:\n$user ~~-~~ username\n$mention ~~-~~ user mention\n$guild ~~-~~ nome do server\n$membercount ~~-~~ contagem novo membro',
    setMessage: 'Mensagem de entrada definida para:\n',
  },
  leave: {
    title: 'Comando leave',
    help: ['leave channel** ~~-~~ Define o canal que as mensagem vão ser enviadas\n**', 'leave message** ~~-~~ Define a mensagem que vai ser enviado quando os users saiem\n\nPodes usar estes comandos na mensagem:\n$user ~~-~~ username\n$mention ~~-~~ user mention\n$guild ~~-~~ nome do server\n$membercount ~~-~~ contagem novo membro'],
    channel: ['leave channel #channel** ~~-~~ Define o canal que as mensagens de saida serão enviadas\n\nPara parar de enviar mensagem para o canal, digite **', 'leave channel stop**'],
    stop: 'Leave messages will stop being sent.',
    setChannel: ['Channel set to <#', '>\n\n**NOTA:** Se a Zira não poder enviar mensagens para o canal, as mensagens de saida estarão desativadas.'],
    message: 'leave message [message]** ~~-~~ Define a mensagem que vai ser enviada quando o user sair\n\nPodes usar estes comandos na mensagem:\n$user ~~-~~ username\n$mention ~~-~~ user mention\n$guild ~~-~~ nome do server\n$membercount ~~-~~ contagem novo membro',
    setMessage: 'Mensagem de saida definida para:\n',
  },
  auto: {
    title: 'Cargo Auto',
    help: ['autorole show** ~~-~~ mostra os cargos definidos\n**', 'autorole user** ~~-~~ adiciona ou remove cargos atribuido quando o user entra\n**', 'autorole bot** ~~-~~ adiciona ou remove cargos atribuido quando o bot entra'],
    user: 'autorole user [@cargo | nome do cargo]** ~~-~~ add or remove a role that should be given when a user joins\n\nTo remove a role that has been set do the above command.',
    userAdd: ['Cardo <@&', '> adicionado irá ser atribuido quando o user entra.\n\n**NOTA:** The `Zira` role needs to be above the role you\'ve set, and needs to have the `Manage Roles` permission to give this role.'],
    userRemove: ['Cardo removido <@&', '> deixou de ser atribuido quando o user entra.'],
    botAdd: ['Cardo <@&', '> adicionado irá ser atribuido quando um bot é convidado.\n\n**NOTA:** The `Zira` role needs to be above the role you\'ve set, and needs to have the `Manage Roles` permission to give this role.'],
    botRemove: ['Cargo <@&', '> Removido deixou de ser atribuido quando um bot é convidado.'],
    bot: 'autorole bot [@cargo | nome do cargo]** ~~-~~ Adiciona ou remove um cargo que terá sido atribuido ao bot quando foi convidado\n\nPara remover o cargo, digite o comando abaixo.',
    showUser: 'Cargos user',
    showBot: 'Cargos Bot',
    no: 'Sem cargos definidos.',
  },
  reset: {
    title: 'Restaurar Configuração :warning:',
    question: 'Tem a certeza que deseja restaurar as configurações do server?\n**TUDO** as configurações de Zira serão restauradas.\n\nDigite `yes` ou `no`',
    yes: 'As configurações do server foram restauradas.',
    no: 'Nada foi restaurado.',
    perm: 'Apenas o dono do server pode restaurar as configurações do server.',
  },
  list: {
    title: ' Role List',
    cont: 'List Continued',
    null: 'If a message ID is null, either reset your config and read the roles, or join the [support server](https://zira.pw/support).',
    noTitle: 'OwO',
    noDesc: 'What\'s this?',
  },
  remove: {
    help: ['remove [[message ID](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)] [@role | role name]** ~~-~~ remove a role that has been setup by Zira\n\nTo get the message ID that a role is on, do **', 'list**.'],
    setup: 'Unable to remove the role as it either was not setup by Zira, or is not on the specified message.',
    removed: ['<@&', '> removed with the emoji '],
  },
  edit: {
    help: 'edit [[message ID](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)] [new message]** ~~-~~ edit a message sent by Zira',
    read: ['Unable to get the message in <#', '> because I lack the `Read Messages` or `Read Message History` permissions.'],
    unknownGet: 'Unable to get that message in <#',
    unknownEdit: 'Unable to edit the message.',
    no: 'That message can\'t be edited by Zira, as it was not sent by Zira.',
    edited: 'Message has been edited.',
  },
  suggestion: {
    help: ['suggestion #canal** ~~-~~ set a channel that suggestions will be sent to\nIf you want to only allow suggestions to be submitted in one channel, do **', 'suggestion [#suggestion channel] [#submit channel]**\n\nTo disable suggestions, do **', 'suggestion stop**'],
    set: ['Suggestion channel set to <#', '>\n\n**NOTE:** If Zira is not able to send messages to the channel, suggestions will be disabled.'],
    setsubmit: ['Suggestion channel set to <#', '> and suggestions can only be submitted in <#', '>\n\n**NOTE:** If Zira is not able to send messages to the channel, suggestions will be disabled.'],
    stop: 'Suggestions are now disabled.',
    disable: 'Suggestions are disabled.',
    notSetup: 'That message is not a suggestion sent by Zira.',
    reason: 'Reason',
    useChannel: ['Use the channel <#', '> to submit a suggestion.'],
    noReason: 'No reason was provided.',
  },
  submit: {
    help: 'submit [sugestão]** ~~-~~ envia sua maravilhosa sugestão',
    title: 'Novas Sugestão',
  },
  approve: {
    help: 'approve [[ID mensagem](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)] [motivo]** ~~-~~ Aprovar uma sugestão',
    read: ['Impossivel aprovar a sugestão em <#', '> porque não tenho permissões para `Ler Mensagens` ou `Ler Historico das Mensagens`.'],
    title: 'Sugestão Aprovada',
    reason: 'Motivo',
    unknown: 'Unable to approve suggestion.',
  },
  deny: {
    help: 'deny [[ID mensagem](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)] [motivo]** ~~-~~ Recusar uma sugestão',
    read: ['Impossivel recusar a sugestão em <#', '> porque não tenho permissões para `Ler Mensagens` ou `Ler Historico das Mensagens`.'],
    title: 'Sugestão Recusada',
    unknown: 'Impossivel recusar a sugestão.',
  },
  maybe: {
    help: 'maybe [[ID mensagem](https://support.discordapp.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID-)] [motivo]** ~~-~~ Possivelmente aprovar uma sugestão',
    read: ['Impossivel possivelmente aprovar a sugestão em <#', '> porque não tenho permissões para `Ler Mensagens` ou `Ler Historico das Mensagens`.'],
    title: 'Sugestão com Potencial',
    unknown: 'Impossivel potencialmente aprovar a sugestão.',
  },
  once: {
    help: 'once [emoji] [@role | role name]** ~~-~~ add a role with an emoji that can only be claimed once to the set message\n\nThis is useful for accepting guild rules, etc.',
    cannotRead: ['Unable to react to the message in <#', '> because I lack the `Read Messages` or `Read Message History` permissions.'],
    cannotReact: ['Unable to react to the message in <#', '> because I lack the `Add Reaction` permission.'],
    unknown: 'Unable to react to the message in <#',
    set: ['<@&', '> added with the emoji ', '\n\n**NOTE:** The `Zira` role needs to be above the role you\'ve set, and needs to have `Manage Roles` permission to give this role.'],
    emoji: 'That emoji is already in use on this message.',
    role: 'That role is already in use on this message.',
  },
  purge: {
    amount: 'You didn\'t input an amount of messages.',
    wrongAmount: 'The amount of messages can only be between 2 - 100.',
    error: 'Couldn\'t purge messages.',
  },

};
